#!/bin/sh

NAME=zabbix-java
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/home/zabbix/bin
DAEMON=/usr/local/sbin/zabbix_java/startup.sh
DOWN=/usr/local/sbin/zabbix_java/shutdown.sh
DESC="Zabbix Java Gateway daemon"
PID=/tmp/zabbix_java.pid

test -f $DAEMON || exit 0

set -e

case "$1" in
  start)
        echo "Starting $DESC"
        $DAEMON
        ;;
  stop)
        echo "Stopping $DESC"
        $DOWN
        ;;
  *)
        N=/etc/init.d/$NAME
        # echo "Usage: $N {start|stop}" >&2
        echo "Usage: $N {start|stop}" >&2
        exit 1
        ;;
esac
exit 0
